apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-v2
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
      version: v2
  template:
    metadata:
      labels:
        app: product-catalog
        version: v2
    spec:
      containers:
      - name: product-catalog
        image: rslim087/product-catalog:2.0.0
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_HOST
          value: "mongodb-product-catalog"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: "product_catalog"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-product-catalog
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-product-catalog
      version: v1
  template:
    metadata:
      labels:
        app: mongodb-product-catalog
        version: v1
    spec:
      containers:
      - name: mongodb-product-catalog
        image: mongo:6.0
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-product-catalog
  namespace: ecommerce
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb-product-catalog
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: product-catalog
  namespace: ecommerce
spec:
  host: product-catalog
  subsets:
  - name: version-1-pods
    labels:
      version: v1
  - name: version-2-pods
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-catalog
  namespace: ecommerce
spec:
  hosts:
  - product-catalog
  http:
  - route:
    - destination:
        host: product-catalog
        subset: version-1-pods
      weight: 80
    - destination:
        host: product-catalog
        subset: version-2-pods
      weight: 20

# So its like we have a service product-catalog that got all pods with label selector: app: product-catalog so now in destination rule we mention host: product-catalog (the name of service that got all product-catalog pods) now we make subsets here by making a subset version-1-pods telling that now pick pods that has lable version: v1 and we make another subnet version-2-pods telling that now pick pods that has lable version: v2 and then in virtual service we mention host: product-catalog (the name of service that got all product-catalog pods) and then we route traffic to these subsets by mentioning the weightage of traffic to be sent to each subset. In this case 80% traffic will be sent to version-1-pods and 20% traffic will be sent to version-2-pods.